
name: Run DB update scripts Stage1

on:
 
 workflow_dispatch:
  
  
jobs:
  Sonar-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build with Gradle
      env: # Or as an environment variable
        TEST_VAR: 'test123'
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      run: ./gradlew printVariable -P environmentName=stage1 -P environment=qa
